AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket with environment tagging'

Parameters:
  Enviroment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: '${AWS::StackName}-${Enviroment}-bucket'  # Correcting 'Environment' to 'Enviroment'
      Tags:
        - Key: Enviroment
          Value: Enviroment
        - Key: Project
          Value: GithubActionsTesting

Outputs:
  BucketName:
    Description: 'Name of the created S3 bucket'  # Corrected typo in 'Description'
    Value: MyS3Bucket
