name: Deploy AWS Lambda

on: 
  push:
    branches:
      - main
    paths:
      - 'lambda/'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target=lambda/ -r lambda/requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Verify AWS CLI Installation
        run: aws --version  # Ensures AWS CLI is available

      - name: Deploy Lambda Function
        run: |
          cd lambda
          zip -r lambda.zip . -x "*.git*" "*__pycache__*" "*.zip"
          ls -lh lambda.zip  # Verify ZIP file size and existence
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://$(pwd)/lambda.zip
